### Goal (arguments) definition
# terrain to traverse
convex_plane_decomposition_msgs/PlanarTerrain terrain
# start and goal configurations
SingleRigidBody start_state
SingleRigidBody goal_state
---
### Result (return values) definition
# trajectory containing the generated trajectory at each timestep
towr_ros/InitialGuessArray initial_guesses
# The contact data for each foot at each timestep
towr_ros/FootstepPlan footstep_plan
---
### Feedback
# int32[] sequence